
package radars;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SystemeAmendesImplService", targetNamespace = "http://radars/", wsdlLocation = "http://localhost:9999/ws/amendes?wsdl")
public class SystemeAmendesImplService
    extends Service
{

    private final static URL SYSTEMEAMENDESIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SYSTEMEAMENDESIMPLSERVICE_EXCEPTION;
    private final static QName SYSTEMEAMENDESIMPLSERVICE_QNAME = new QName("http://radars/", "SystemeAmendesImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/ws/amendes?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SYSTEMEAMENDESIMPLSERVICE_WSDL_LOCATION = url;
        SYSTEMEAMENDESIMPLSERVICE_EXCEPTION = e;
    }

    public SystemeAmendesImplService() {
        super(__getWsdlLocation(), SYSTEMEAMENDESIMPLSERVICE_QNAME);
    }

    public SystemeAmendesImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SYSTEMEAMENDESIMPLSERVICE_QNAME, features);
    }

    public SystemeAmendesImplService(URL wsdlLocation) {
        super(wsdlLocation, SYSTEMEAMENDESIMPLSERVICE_QNAME);
    }

    public SystemeAmendesImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SYSTEMEAMENDESIMPLSERVICE_QNAME, features);
    }

    public SystemeAmendesImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SystemeAmendesImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SystemeAmendes
     */
    @WebEndpoint(name = "SystemeAmendesImplPort")
    public SystemeAmendes getSystemeAmendesImplPort() {
        return super.getPort(new QName("http://radars/", "SystemeAmendesImplPort"), SystemeAmendes.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SystemeAmendes
     */
    @WebEndpoint(name = "SystemeAmendesImplPort")
    public SystemeAmendes getSystemeAmendesImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://radars/", "SystemeAmendesImplPort"), SystemeAmendes.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SYSTEMEAMENDESIMPLSERVICE_EXCEPTION!= null) {
            throw SYSTEMEAMENDESIMPLSERVICE_EXCEPTION;
        }
        return SYSTEMEAMENDESIMPLSERVICE_WSDL_LOCATION;
    }

}
